#!/bin/bash

# Directorio de destino
DEST_DIR="/tmp/u"

# Mover archivos que comienzan con mayúscula
for file in [A-Z]*; do
    # Comprobar si el archivo existe (para evitar mover directorios vacíos)
    if [ -f "$file" ]; then
        mv "$file" "$DEST_DIR/"
    fi
done
